
# Streamlit Secrets File

[general]
# Put your secrets below

OPENAI_API_KEY = "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""
